name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: List files (debug)
        run: |
          pwd
          ls -la
          echo "---- tests dir ----"
          ls -la tests || true
          echo "---- show test files tracked by git ----"
          git ls-files tests || true
          git ls-files "tests/*.py" || true

      - name: Run tests
        run: pytest -q tests
